CREATE TABLE [dbo].[Game]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Title VARCHAR(100) NOT NULL,
	Genre VARCHAR(50),
	ReleaseYear INT,
	Note INT NOT NULL
	CONSTRAINT CK_Note CHECK (Note BETWEEN 0 AND 5)
)
